//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.27 at 11:08:52 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.um.es/sondeo")
package usuario;
