//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.27 at 11:42:58 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.um.es/sondeo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package sondeo;
