//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.29 at 07:02:42 PM CEST 
//


package tipos;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="respuesta" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="entrada" type="{http://www.um.es/sondeo}Entrada" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="usuario" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pregunta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="instrucciones" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="apretura" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="cierre" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="minSeleccion" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="maxSeleccion" type="{http://www.w3.org/2001/XMLSchema}int" default="2" />
 *       &lt;attribute name="visibilidad" default="siempre">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="siempre"/>
 *             &lt;enumeration value="participantes"/>
 *             &lt;enumeration value="fecha"/>
 *             &lt;enumeration value="nunca"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "respuesta",
    "entrada"
})
@XmlRootElement(name = "TipoSondeo")
public class TipoSondeo {

    @XmlElement(required = true)
    protected List<String> respuesta;
    @XmlElement(required = true)
    protected List<Entrada> entrada;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "usuario", required = true)
    protected String usuario;
    @XmlAttribute(name = "pregunta", required = true)
    protected String pregunta;
    @XmlAttribute(name = "instrucciones")
    protected String instrucciones;
    @XmlAttribute(name = "apretura", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar apretura;
    @XmlAttribute(name = "cierre", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cierre;
    @XmlAttribute(name = "minSeleccion")
    protected Integer minSeleccion;
    @XmlAttribute(name = "maxSeleccion")
    protected Integer maxSeleccion;
    @XmlAttribute(name = "visibilidad")
    protected String visibilidad;

    /**
     * Gets the value of the respuesta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the respuesta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRespuesta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRespuesta() {
        if (respuesta == null) {
            respuesta = new ArrayList<String>();
        }
        return this.respuesta;
    }

    /**
     * Gets the value of the entrada property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entrada property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntrada().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Entrada }
     * 
     * 
     */
    public List<Entrada> getEntrada() {
        if (entrada == null) {
            entrada = new ArrayList<Entrada>();
        }
        return this.entrada;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the usuario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * Sets the value of the usuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsuario(String value) {
        this.usuario = value;
    }

    /**
     * Gets the value of the pregunta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPregunta() {
        return pregunta;
    }

    /**
     * Sets the value of the pregunta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPregunta(String value) {
        this.pregunta = value;
    }

    /**
     * Gets the value of the instrucciones property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrucciones() {
        return instrucciones;
    }

    /**
     * Sets the value of the instrucciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrucciones(String value) {
        this.instrucciones = value;
    }

    /**
     * Gets the value of the apretura property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getApretura() {
        return apretura;
    }

    /**
     * Sets the value of the apretura property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setApretura(XMLGregorianCalendar value) {
        this.apretura = value;
    }

    /**
     * Gets the value of the cierre property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCierre() {
        return cierre;
    }

    /**
     * Sets the value of the cierre property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCierre(XMLGregorianCalendar value) {
        this.cierre = value;
    }

    /**
     * Gets the value of the minSeleccion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMinSeleccion() {
        if (minSeleccion == null) {
            return  0;
        } else {
            return minSeleccion;
        }
    }

    /**
     * Sets the value of the minSeleccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinSeleccion(Integer value) {
        this.minSeleccion = value;
    }

    /**
     * Gets the value of the maxSeleccion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxSeleccion() {
        if (maxSeleccion == null) {
            return  2;
        } else {
            return maxSeleccion;
        }
    }

    /**
     * Sets the value of the maxSeleccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxSeleccion(Integer value) {
        this.maxSeleccion = value;
    }

    /**
     * Gets the value of the visibilidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisibilidad() {
        if (visibilidad == null) {
            return "siempre";
        } else {
            return visibilidad;
        }
    }

    /**
     * Sets the value of the visibilidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisibilidad(String value) {
        this.visibilidad = value;
    }

}
